accounts/urls.py
from django.urls import path

from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/',  UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

exam_8/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, DetailProductView, CreateProductView, UpdateProductView, DeleteProductView, \
    CreateReviewView, UpdateReviewView, DeleteReviewView, ListNoModeratedReviewView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', DetailProductView.as_view(), name="product_detail"),
    path('product/add/', CreateProductView.as_view(), name="product_create"),
    path('product/<int:pk>/update/', UpdateProductView.as_view(), name="product_update"),
    path('product/<int:pk>/delete/', DeleteProductView.as_view(), name="product_delete"),
    path('product/<int:pk>/review_add/', CreateReviewView.as_view(), name="review_create"),
    path('review/<int:pk>/update/', UpdateReviewView.as_view(), name="review_update"),
    path('review/<int:pk>/delete/', DeleteReviewView.as_view(), name="review_delete"),
    path('reviews/no_moderated/', ListNoModeratedReviewView.as_view(), name="no_moderated_reviews")
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

CHOICES = [('other', 'Разное'), ('electronics', 'Электроника'), ('Services', 'Услуги'), ('Books', 'Книги')]


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    category = models.CharField(max_length=20, default='other', choices=CHOICES, verbose_name='Категории')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(verbose_name='Картинка', upload_to='pictures', null=True, blank=True)

    def get_avg(self):
        result = self.reviews.filter(is_moderated=True).aggregate(avg=Avg('rating'))
        if not result['avg']:
            result['avg'] = 0
        return result['avg']

    def __str__(self):
        return f"{self.name} - {self.category}"


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews',
                                verbose_name='Товар')
    text = models.TextField(max_length=2000, verbose_name='Текст отзыва')
    rating = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(1), MaxValueValidator(5)])
    is_moderated = models.BooleanField(default=False, verbose_name='Подтвержден')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        permissions = [("view_not_moderated_review", "Видеть немодерированные отзывы")]

    def __str__(self):
        return f"{self.author.username} - {self.product.name}"

webapp/forms.py
from django import forms

from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'picture']


class UserReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']


class ModeratorReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating', 'is_moderated']

webapp/views/products.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

from webapp.models import Product
from webapp.forms import ProductForm


class IndexView(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 3


class DetailProductView(DetailView):
    model = Product
    template_name = 'product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()

        if not self.request.user.has_perm('webapp.view_not_moderated_review'):
            reviews = reviews.filter(is_moderated=True)

        context['reviews'] = reviews.order_by('-edited_at')
        return context


class CreateProductView(PermissionRequiredMixin, CreateView):
    form_class = ProductForm
    model = Product
    template_name = 'product/create.html'
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class UpdateProductView(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'product/update.html'
    permission_required = 'webapp.change_product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class DeleteProductView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'

webapp/views/reviews.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from webapp.models import Review, Product
from webapp.forms import UserReviewForm, ModeratorReviewForm


class CreateReviewView(LoginRequiredMixin, CreateView):
    form_class = UserReviewForm
    model = Review
    template_name = 'review/create.html'

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        author = self.request.user
        form.instance.author = author
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class UpdateReviewView(PermissionRequiredMixin, UpdateView):
    form_class = UserReviewForm
    model = Review
    template_name = 'review/update.html'
    permission_required = 'webapp.change_review'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_form_class(self):
        if self.request.user.has_perm('webapp.change_review'):
            return ModeratorReviewForm
        return UserReviewForm

    def form_valid(self, form):
        if not self.request.user.has_perm('webapp.change_review'):
            form.instance.is_moderated = False
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class DeleteReviewView(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'review/delete.html'
    permission_required = 'webapp.delete_review'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class ListNoModeratedReviewView(PermissionRequiredMixin, ListView):
    model = Review
    template_name = 'review/no_moderated.html'
    context_object_name = 'reviews'
    permission_required = 'webapp.view_not_moderated_review'

    def get_queryset(self):
        return super().get_queryset().filter(is_moderated=False)

webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}Главная страница{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}{% endblock %}
                {% if perms.webapp.add_product %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:product_create' %}">Добавить продукт</a>
                    </li>
                {% endif %}
                {% if perms.webapp.view_not_moderated_review %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:no_moderated_reviews' %}">Непромодерированные отзывы</a>
                    </li>
                {% endif %}

            </ul>

            {% if request.user.is_authenticated %}
                    <p class="ms-auto text-secondary d-inline-block my-0 py-auto" >Привет, <a href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}</a></p>
                    <a class="btn btn-dark ms-2" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выйти</a>
            {% else %}
                    <a class="btn btn-dark ms-auto" href="{% url 'accounts:login' %}?next={% if request.GET.next  %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Войти</a>
                    <a class="btn btn-outline-secondary ms-2" href="{% url 'accounts:create' %}?next={% if request.GET.next  %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>