exam_8/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, DetailProductView, CreateProductView, UpdateProductView, DeleteProductView, \
    CreateReviewView, UpdateReviewView, DeleteReviewView, ListNoModeratedReviewView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', DetailProductView.as_view(), name="product_detail"),
    path('product/add/', CreateProductView.as_view(), name="product_create"),
    path('product/<int:pk>/update/', UpdateProductView.as_view(), name="product_update"),
    path('product/<int:pk>/delete/', DeleteProductView.as_view(), name="product_delete"),
    path('product/<int:pk>/review_add/', CreateReviewView.as_view(), name="review_create"),
    path('review/<int:pk>/update/', UpdateReviewView.as_view(), name="review_update"),
    path('review/<int:pk>/delete/', DeleteReviewView.as_view(), name="review_delete"),
    path('reviews/no_moderated/', ListNoModeratedReviewView.as_view(), name="no_moderated_reviews")
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

CHOICES = [('other', 'Разное'), ('electronics', 'Электроника'), ('Services', 'Услуги'), ('Books', 'Книги')]


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    category = models.CharField(max_length=20, default='other', choices=CHOICES, verbose_name='Категории')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(verbose_name='Картинка', upload_to='pictures', null=True, blank=True)

    def get_avg(self):
        result = self.reviews.filter(is_moderated=True).aggregate(avg=Avg('rating'))
        if not result['avg']:
            result['avg'] = 0
        return result['avg']

    def __str__(self):
        return f"{self.name} - {self.category}"


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews',
                                verbose_name='Товар')
    text = models.TextField(max_length=2000, verbose_name='Текст отзыва')
    rating = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(1), MaxValueValidator(5)])
    is_moderated = models.BooleanField(default=False, verbose_name='Подтвержден')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        permissions = [("view_not_moderated_review", "Видеть немодерированные отзывы")]

    def __str__(self):
        return f"{self.author.username} - {self.product.name}"

webapp/forms.py
from django import forms

from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'picture']


class UserReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']


class ModeratorReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating', 'is_moderated']

webapp/views/products.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

from webapp.models import Product
from webapp.forms import ProductForm


class IndexView(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 3


class DetailProductView(DetailView):
    model = Product
    template_name = 'product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()

        if not self.request.user.has_perm('webapp.view_not_moderated_review'):
            reviews = reviews.filter(is_moderated=True)

        context['reviews'] = reviews.order_by('-edited_at')
        return context


class CreateProductView(PermissionRequiredMixin, CreateView):
    form_class = ProductForm
    model = Product
    template_name = 'product/create.html'
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class UpdateProductView(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'product/update.html'
    permission_required = 'webapp.change_product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class DeleteProductView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'

webapp/views/reviews.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from webapp.models import Review, Product
from webapp.forms import UserReviewForm, ModeratorReviewForm


class CreateReviewView(LoginRequiredMixin, CreateView):
    form_class = UserReviewForm
    model = Review
    template_name = 'review/create.html'

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        author = self.request.user
        form.instance.author = author
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class UpdateReviewView(PermissionRequiredMixin, UpdateView):
    form_class = UserReviewForm
    model = Review
    template_name = 'review/update.html'
    permission_required = 'webapp.change_review'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_form_class(self):
        if self.request.user.has_perm('webapp.change_review'):
            return ModeratorReviewForm
        return UserReviewForm

    def form_valid(self, form):
        if not self.request.user.has_perm('webapp.change_review'):
            form.instance.is_moderated = False
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class DeleteReviewView(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'review/delete.html'
    permission_required = 'webapp.delete_review'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.product.pk})


class ListNoModeratedReviewView(PermissionRequiredMixin, ListView):
    model = Review
    template_name = 'review/no_moderated.html'
    context_object_name = 'reviews'
    permission_required = 'webapp.view_not_moderated_review'

    def get_queryset(self):
        return super().get_queryset().filter(is_moderated=False)

webapp/templates/product/delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Вы действительно хотите удалить {{ product.name }}?</h2>
    <form action="" method="POST">
    {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
        <a href="{% url 'webapp:product_detail' product.pk %}" class="btn btn-success">Нет</a>
    </form>
{% endblock %}

webapp/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}
    {% if perms.webapp.change_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product_update' product.pk %}">Изменить</a>
        </li>
    {% endif %}
    {% if perms.webapp.delete_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a>
        </li>
    {% endif %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:review_create' product.pk %}">Оставить отзыв</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="card m-3">
        <div class="row g-0">
            <div class="col-md-4">
                {% if product.picture %}
                    <img src="{{ product.picture.url }}" class="card-img-top">
                {% else %}
                    <img src="{% static "images/no_picture.jpg" %}" class="card-img-top">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }} | <span>{{ product.get_avg }}</span></h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text"><small class="text-muted">{{ product.category }}</small></p>
                </div>
            </div>
        </div>
    </div>

    {% include 'partial/rewiews_list_partial.html' %}
{% endblock %}

webapp/templates/product/index.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Продукты</h1>
    <div class="row">

        {% for product in products %}
            <div class="col-sm-4">
                <div class="card">
                    {% if product.picture %}
                        <img src="{{ product.picture.url }}" class="card-img-top">
                    {% else %}
                        <img src="{% static "images/no_picture.jpg" %}" class="card-img-top">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }} | <span>{{ product.get_avg }}</span></h5>

                        <a href="{% url 'webapp:product_detail' product.pk %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
    {% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}
{% endblock %}